language: node_js
node_js:
- 7.8
script:
- printf 'configs/\nsrc/\n.npmignore\n.travis.yml\nCHANGELOG.md\nGruntfile.js\nbower.json\nLICENSE-MIT\npackage.json\nnode_modules/\n.gitignore\ndeployed*' > .gitignore
- printf '.npmignore\n.travis.yml\nCNAME' > .npmignore
- printf 'stickme.martinmetodiev.com' > CNAME
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
- provider: npm
  email: metodiev.martin@gmail.com
  api_key:
    secure: 1dRWzhzpdLq5Qomv63bC2VthAXt2aF+0rUWJ4DFLIUgDeLeh0QN32sJ2wSKixD6VhWVjy7R9kJ/pp6chvC6NGI6bwc1UYZiBW1IfJtPtBePX5p+FlQw/f0/P5ItSH0OkpZCMSKObfivusGvxEpeCnDMuRtJ1vOjiOhqHltl3m6WH7hgwUIV3FMplPeK9/eSh6nEUC96BgIhlsKrmUQDbsDZfQ193xJuH0TDNXhxXpsiVXF7urSbgqornrUkE362xyySu3mxusXyHhE3ImPygiMfCnucY4GbbkR1/I7qrNkBinqEBeU345U4rkj5lXGQ4/u2dRP7CoOhClJzompHgBheQjDf9BKgJBTs3x7YT7iHqrGjk6AzaANfr8ZG0NK0BqBI6cCkRdCLYszCnA87knSCAkwuN53cXUA/im699xUtV7+z6Udjo1qK5pM3TaPZIUbrAoIcS0sst4fAJergdUz5OLrzXgt86KvhosRvYNoRoi7YgQtMkMQrJUxh8PEI6XKB0R6ihth1ROI2h9S2wI34nnvSAPYM7uHmjrxjY6VXC5wuQvjL+cpQJbHl41Jr3rvSzJgCaSOXFwAjmQ4Ua5N2n/wK5qJgjVsHU0GZYWdlZTHTp6BBQo3V0swXBiU2liaAXZ0G2M9WLnhHxgWSzta/VhX7rWuVwqPwbXCqcc6A=
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  github_token:
    secure: SDGWiukaHPaXSV9cXaADPNSEl+uK+dT3nL3ypQ+CvkrBN//mIVYBxWQB7MEqanLGB9iQso06I+b7XBeznydN/bn6dI9H6mv/yXcwgxvkPCXanmdckzQLAzY94mMFmmoDrHogMufNZhvZNXcFgVPlRGr1qPzlpVecgoqNlsEa+5gdzJ1757GHGVZw408MFvM4FMXNKQYanCbZv+9z8GIGkUqiPnOYFeLf0qsHeRPs+DFbWRGx2gwyJ5Ahar1+3ztwUj7blIwNPhc40hMQ89xy1aPbRkpptbGFVknyYNFcWOH0gbkwTt2AT3lRmqZ6nYtrHHAV+cF0nkMmNQWhNHIZZVFPuIP37Xx8F5rOlHaAaotswXOMNT4SIB8iIjmV4JrSVCXz0frzqM2q7z+/9Uf7TerOI3Whhpbr9xHhOnLzXLGkhzFRJFiIlaDCRHcKam2oUdq+umEwZg+0IoLXtJlj4okoJCq+KeuasMoFsqBAgvrBfpoxrnE7a5d23ZS/WGW/0TIwePZ83B2u+PUYHVEEhKHod/2HFqYz+T7tG2QKhdZrLQZotA/muIWiMgj51GomTvSAhS3xFWqZ0phAjX6Ljm4yR5oCBE6uzfmQ4DUni7NyNFAePx3kAyBrG0tud7Z/m5uPoTzaZUDshtOYLCT1MSSs7PJoat0O1la40S6ZizU=
  on:
    tags: true
- provider: releases
  api_key:
    secure: SDGWiukaHPaXSV9cXaADPNSEl+uK+dT3nL3ypQ+CvkrBN//mIVYBxWQB7MEqanLGB9iQso06I+b7XBeznydN/bn6dI9H6mv/yXcwgxvkPCXanmdckzQLAzY94mMFmmoDrHogMufNZhvZNXcFgVPlRGr1qPzlpVecgoqNlsEa+5gdzJ1757GHGVZw408MFvM4FMXNKQYanCbZv+9z8GIGkUqiPnOYFeLf0qsHeRPs+DFbWRGx2gwyJ5Ahar1+3ztwUj7blIwNPhc40hMQ89xy1aPbRkpptbGFVknyYNFcWOH0gbkwTt2AT3lRmqZ6nYtrHHAV+cF0nkMmNQWhNHIZZVFPuIP37Xx8F5rOlHaAaotswXOMNT4SIB8iIjmV4JrSVCXz0frzqM2q7z+/9Uf7TerOI3Whhpbr9xHhOnLzXLGkhzFRJFiIlaDCRHcKam2oUdq+umEwZg+0IoLXtJlj4okoJCq+KeuasMoFsqBAgvrBfpoxrnE7a5d23ZS/WGW/0TIwePZ83B2u+PUYHVEEhKHod/2HFqYz+T7tG2QKhdZrLQZotA/muIWiMgj51GomTvSAhS3xFWqZ0phAjX6Ljm4yR5oCBE6uzfmQ4DUni7NyNFAePx3kAyBrG0tud7Z/m5uPoTzaZUDshtOYLCT1MSSs7PJoat0O1la40S6ZizU=
  skip_cleanup: true
  on:
    tags: true
