language: node_js
node_js:
- node
script:
- printf 'configs/\nsrc/\n.npmignore\n.travis.yml\nCHANGELOG.md\nGruntfile.js\nbower.json\nLICENSE-MIT\npackage.json\nnode_modules/\n.gitignore\ndeployed*' > .gitignore
- printf '.npmignore\n.travis.yml\nCNAME' > .npmignore
- printf 'stickme.martinmetodiev.com' > CNAME
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
- provider: npm
  email: metodiev.martin@gmail.com
  api_key: # …73e2f34c
    secure: cXop3Qnx9YZNk9WbYUsKBtXbXRroyp5NfkHqeaCqgZ6OFPvyy7ZNZSR19snkL+iCeVa1SLGChCbomYer5VSF+9dbil7N7odqqBPEqlu4wcQ7fFZLPzJW+EUjlIjw26+2x29aP76R8h7PZdM/divCG7TJXHl5SLX3QePs4Hm/PMYF55dmq03UWlSrqQr4KaPY+Lti9TOUIpab03NtHXsPSrDBqp1YJP/UW/r8VUDwOLzD8s4mQIznor2fVJ/baEnGTt16CRZ5/00kvJHNucM/Sjo74Ibz0BzyPy24aDs4II6LQbjIisbGR8EaOgZ7Z2iXTcWWzNIjpg0PlsxDpC0ExJxi8Tqit9JkvZCRPV/fq649rbBQWt05BtE8oJQ6t6ClcE0bn9WBbZpQhnvf/POeER9NsGJkeoyj31aZr1S0NKrqFR/KfumtUJIQLzKB19gH7XK5arhjBTJ+XFx6f0hLmQAmFhB6TMhxkyJZi2X7M6a/32NBi5yBpWn1ltaPvY6piWJZUyvof7iVxaIMZwt76+2nZ2s0OGFJ8FCWNmZHpRYEINg9AjCI5aYbo7FrehpuHo2FP44HGsZft6IeBpVQ14yTvGjYzqOuE9MlJHYEJv1B99uD5m+5AI8cnf3gNL4+8d2uc0f0PLJVwhZLFikXyPFpVBYgGEFvWOadqmduloY=
  on:
    tags: true
    all_branches: true
- provider: pages
  skip_cleanup: true
  github_token:
    secure: pa4vJZcgYcxgZWRpjUQh4DMVRFJ83b6vwM50cFwCgVtEK9ZPpIeJ7/91Jn2zDaa3KbVUfJU0FQruaql6lJWQJBgksHKeNK0lUZb2PfV+IWc4zQ5DOnT1l9c83g5o2NUOSuqmm31L5CfQdu+m3GbsPVSh7/q+NUwPhwVduPomzOWv7BNSaUkiDRWaWX35Ibq2AtKrQCjzUlj/EraRFohRVpauJjPxyl6IcMvXaC06zlWHOe+UrT9I6g+q+GMO1x4LPejxWeij2MNeoYhQZjHCmwR6Toti14Xkyyc+ccEXDuU9jKc/vLqMKDnw9K9YZ74tTTQGcb84BvOVnKuHXZMjeZme/rRSOtKllIlBdZdijA7ClYhyyjzYREzuZfR2wKNKwZzfVpMb0jp1dujZg2q81C+m4fYbDvURtSOkPIqv+lV7YDQHSSiRrtFcAQ1EA5h1ENLAOb+iM6aVsFykBa48q32vp95VTL1cc5p/WfaA5Kw7fiTOBUecMFHOWr4uR5LEam1aMVy5qawHTMO/7Qw7bHXP8167eynn9JArS+uOcU36Y2ez3Yb3TLnblwkXRtq/Fqg2YeToD+onIHqNMLH+QbWX3rh9TCXYdSYKkpdSG09eftRjsWU4y1tXz178S/yVLb71ZQdONMGKyuA3CLcLdOmrn9uL2Pxk58arFytixO4=
  on:
    tags: true
- provider: releases
  api_key:
    secure: dDBwS3QDOzkPg0g5MMd2Z3oheCIfZbmjhdibRErUqLHzHMyO1rsuzM0cE8OnnAuH8PvCyv7VHI5XYAJHHqQA9DZo+jRtjMQ//WjU5uKWKvqL5ZW/tXZ/CvbDwLf+htlroSB9QsoF/rfs+z92wGFfJaY4dzJ+Mo35w9kee/J6vv3hp0tCWBpn6kkmojeaIvFjzCbadpnHV5R9tXLQzX+2NKC2fj+EoAvENhFSGH7UE/fjU9sQfe9jI9FKUZVpotNwr3G/L+rNfHI1RvA8AtQBlhzVaidHjs/sF165+Z79o+vz0fQbQDPrpJFV0sQpivyuDRqIQcvbyj+RDHdYK0xQ+Z0UqwmOEaDY7Wkih7COWIdc2IgdanWKHCqlyVJu6qu/QMJzPytaB+2sv4tvlwqw6AOy8+WuedfsVR6kATAyzFWXgaZS2kAOwuiwB9zfksuOIUe34DWofReq7RL9o7MTLkN49t52NGddNGj0nbifwjz00nzFG5mKuHU+SEizrFWNQdu7+BVH74nJleTWyVjci4R3HxMNiNIXLwUOr89+dAVPF48ECFdX6hGsVklIiAmz56IOqWhGf6wwajOTWyGw8viKcP0uLYdy46zf/nl0Ekx/SBFc1uGInvtnAlN1/lv9ZTWIZc9t66Ku5qXcs7yrddb0XMe7b3u383g7DNK2c3w=
  skip_cleanup: true
  on:
    tags: true
